resolver: nightly-2020-06-25

packages:
  - .

extra-deps:
  # numhask pack
  - git: https://github.com/tonyday567/numhask
    commit: 1dcb82dc7e503605bac193c64fe82c1b35ca9fcd

  # box pack
  - git: https://github.com/tonyday567/box
    commit: 34819c01063456c9d17178d6ebd3be4cd8ed799d
